version: '3'

services:
    guestbook_database:
        container_name: guestbook_database
        image: mysql:8.0.22
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        volumes:
            - "./var/databases:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=guestbook
            - MYSQL_USER=app_user
            - MYSQL_PASSWORD=secret

    guestbook_phpmyadmin:
        container_name: guestbook_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 8010:80
        depends_on:
            - guestbook_database
        environment:
            PMA_HOST: guestbook_database
            PMA_PORT: 3306

    guestbook_rabbitmq:
        container_name: guestbook_rabbitmq
        image: rabbitmq:3.8.9-management
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            - RABBITMQ_DEFAULT_USER=app_user
            - RABBITMQ_DEFAULT_PASS=secret
            - RABBITMQ_DEFAULT_VHOST=guestbook_vhost

    guestbook_mailer:
        image: schickling/mailcatcher
        ports:
            - 1025:1025
            - 1080:1080
